### ISSUE TITLE
can't get favicon to work with shinydashboard

### ISSUE THREAD

**Issue by HarlanH** [rstudio/shinydashboard#102]
In other Shiny apps, you can put this pattern in the ui.R file to get a favicon to load: `tags$head(tags$link(rel="shortcut icon", href="favicon.ico"))`

With shinydashboard, this doesn't seem to work. I can't tell why. There's no error, but nothing shows up in the page source. If there's no workaround that I'm missing, could support for a favicon be added?

**Comment by micstr** [comment]
Any progress made with this?

I can get it to work locally with placing icon in www directory (see Joes answer (https://groups.google.com/forum/#!searchin/shiny-discuss/favicon%7Csort:relevance/shiny-discuss/Vz3DihUOrfc/EbMG4UeAaHUJ

**Comment by mdbrown** [comment]
I'm adding another squeak to this wheel. I would love to not see the blank document icon on my app!

**Comment by bborgesr** [comment]
This works for me:

```r

# ------------------------- Instructions --------------------------- #
# Restart R with a clean session and open the browser tab each time,
# to make sure this is or isn't working (browsers often cache favicons)
# ------------------------------------------------------------------ #

library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(
    # either do this, or put "favicon.ico" directly in the wwww directory
    # and it will be auto-detected
    tags$head(tags$link(rel = "shortcut icon", href = "favicon.ico"))
  ),
  title = "Dashboard example"
)
server <- function(input, output, session) {}

shinyApp(ui, server)
```

I'm using the latest CRAN version for both shiny and shinydashboard...

**Comment by micstr** [comment]
Thanks @bborgesr, yes this works locally. Please can you confirm if it works on **.shinyapps.io** as well. I still get the vanilla R icon in my browsers despite your code and putting the ico file in  www.

**Comment by bborgesr** [comment]
@micstr, @mdbrown, I just deployed both examples, and I get a blank document favicon in both cases (with the favicon in the www directory):

- https://barbara.shinyapps.io/favicon-shiny/
  ```r
  library(shiny)
  ui <- fluidPage(title = "Shiny example")
  server <- function(input, output, session) {}
  shinyApp(ui, server)
  ```

- https://barbara.shinyapps.io/favicon-shinydashboard/
  ```r
  library(shiny)
  library(shinydashboard)
  ui <- dashboardPage(
    dashboardHeader(),
    dashboardSidebar(),
    dashboardBody(),
    title = "Dashboard example"
  )
  server <- function(input, output, session) {}
  shinyApp(ui, server)
  ```

As you pointed out, both of these work fine locally.

Getting favicons to work generally in browsers is a notoriously frustrating thing, so I think your issue is more generally about favicons not being handled correctly when an app is deployed to shinyapps.io than about shinydashboard.

I'll close the issue here, since there isn't anything different about how shiny and shinydashboard handle favicons (and they both work locally).

I don't know if this is a known issue for rsconnect (the "engine" behind shinyapps.io), but if not, you could certainly [file an issue there](https://github.com/rstudio/rsconnect/issues). You can also create a post in the [shinyapps-users mailing list](https://groups.google.com/forum/#!forum/shinyapps-users).

Sorry I couldn't be of more help.

**Comment by vkresch** [comment]
@bborgesr does it still work or is there currently another workaround to set the icon? I tried your solution but it did not work for me.

**Comment by Sancomania** [comment]
Change the name of the ico to use.

**Comment by Sancomania** [comment]
> Change the name of the ico to use.

IE name the ico in the www folder with a name different than favico
