### ISSUE TITLE
Not able to install Shinydashboard

### ISSUE THREAD

**Issue by sourabhpotnis** [rstudio/shinydashboard#142]
I am trying to install R shinydashboard package and getting following error:
 installing _source_ package ‘shinydashboard’ ...
*\* package ‘shinydashboard’ successfully unpacked and MD5 sums checked
*\* R
*\* inst
*\* preparing package for lazy loading
Error in if (file.size(codeFile) == file.size(loaderFile)) warning("package seems to be using lazy loading already") else { :
  missing value where TRUE/FALSE needed
ERROR: lazy loading failed for package ‘shinydashboard’
 removing ‘/vol_01/sys_apps_01/R/R-3.2.0/library/shinydashboard’

The downloaded source packages are in
        ‘/tmp/RtmpV7HB06/downloaded_packages’
Warning message:
In install.packages("shinydashboard") :
  installation of package ‘shinydashboard’ had non-zero exit status

**Comment by bborgesr** [comment]
You probably figured this out by now, but this error sometimes happens when you attempt to re-install a package that is already installed _and_  that is currently loaded. Just restart you R session for a clean environment and try again. You should encounter no issues. Let me know if there's any problem and we can reopen this.
