### ISSUE TITLE
Feature request: use infoBox and valueBox outside shiny dashboards

### ISSUE THREAD

**Issue by FrancoisGuillem** [rstudio/shinydashboard#171]
I would like to be able to include infoBoxes and valueBoxes in a Rmarkdown file. 

When I try to include an infoBox I get the following error message : `path for html_dependency not provided`. 

When I include a valueBox, there is no error, but the needed CSS is not included in the final document, so the valueBox is not correctly formatted.

**Comment by jacob-ogre** [comment]
I got it to work by including AdminLTE.css from inst/AdminLTE in the YAML header as custom CSS. That works when making direct calls to shinydashboard elements, e.g., `infoBox()`, but not embedded apps.

If you use the embedded Shiny app approach, like the [kmeans_cluster example](http://rmarkdown.rstudio.com/authoring_shiny.html#embedded_applications), then it looks like the CSS from AdminLTE.css has to be included in the embedded app using `tags$head(tags$style(HTML("<css>")))` in ui.R. I think the app is run from a separate `tempdir()` and can't find the path to an external CSS file...neither placing AdminLTE.css in the Rmd root directory or in a www/ location worked. And because the AdminLTE file is ~5000 lines, the full head-style tag approach is...cumbersome.

**Comment by jacob-ogre** [comment]
Welp, the first approach renders fine in the RStudio preview window but not in the Browser (Chrome in this case), but unclear why at the moment. The second approach mostly works in the browser, but there is some CSS interference I haven't yet identified. To work around the unwieldiness of the tags, I created a single-function package--creatively named AdminLTE--to load the CSS inside a `shiny::HTML` tag in ui.R. Will update if I find a better solution.

**Comment by bborgesr** [comment]
Sorry, `shinydashboard` integration with interactive Rmd documents is not something we're working on. While you can try to do this,`shinydashboard` has, as you found out, a lot of JS and CSS and there's a good chance it would conflict with other things on the app. For now, it's probably easier for you to do something that looks like an infoBox/valueBox/... by adding custom CSS than trying to include all the JS and CSS in an app that is not build with AdminLTE to start with.
