### ISSUE TITLE
dropdown menu in shiny dashboard

### ISSUE THREAD

**Issue by parvanesh** [rstudio/shinydashboard#211]
I would like to know if it is possible to convert sidebar menu as top menu (same as navbar in shiny?). The main problem is the drop down items under menu items.I know about:

- tabPanel solution : it is not solving my problem for dropdown lists items under some menu items
- dropdownmenu: it has also the same problem

I appreciate any ideas

**Comment by bborgesr** [comment]
This is an identical request to #224, so I'm giving it the same response:

> Sorry, this is unlikely to be implemented in shinydashboard. This is because this package is tied to a dashboard template, called AdminLTE. So if there is something UI-specific that is not possible in AdminLTE, it is unlikely to be implemented for shinydashboard. This is one of those cases.

Since it seems like there is a fair bit of interest in this feature, we may get to it, but, at best, it is unlikely to happen anytime soon. 

Is there a reason other than the aesthetic look that you have for wanting this? To my knowledge, it is actually not very common to see topside navigation in dashboards (here's a [dashboard gallery](http://www.hongkiat.com/blog/dashboard-design-examples-resources/), where you can see that most dashboard have a sidebar menu). I'd be interested to know what's the motivation behind this.
