### ISSUE TITLE
Plotly graph width & height do not stay within box

### ISSUE THREAD

**Issue by nsittler** [rstudio/shinydashboard#219]
I am having an issue related to a closed post (#164). I just updated my plotly package to 4.7.0.9000 and now the output graphs will not stay within the bounds of a box in my shinydashboard app. Specifying width or height arguments to plotlyOutput do not solve the issue.

Is there a way to force the plot to stay within the bounds of the box? Any help is appreciated.

` box(width = 12, title = tagList(shiny::icon("flask")," Crude Yield:"), status = "primary", solidHeader = TRUE, plotlyOutput("primer_crude_od"))`

An example image where it can be seen that the plot ignores both height and width arguments can be found attached.
![screenshot_060117_010119_pm](https://cloud.githubusercontent.com/assets/5579981/26698326/6c12852a-46ca-11e7-9f89-07f3091bb485.jpg)

**Comment by anushka-123** [comment]
I am also having the same problem. I have installed CRAN version of packages for both ggplot2 and plotly. It is showing a warning message.
**We recommend that you use the dev version of ggplot2 with `ggplotly()`
Install it with: `devtools::install_github('hadley/ggplot2')`.**
It this problem is solved in github version of packages?
P.S: I am not able to install github version. It is showing installation failed because 'tibble' is not available.

**Comment by nicholaelaw** [comment]
Same here. This is what I did to make plotly graphs behave:

- for the height problem, specify a height for both `plotlyOutput` and the parent `box`.
```r
box(
  plotlyOutput('plot01', height = 300L),
  width = 12L, height = 340L
)
```
The trick is, find an appropriate `height` for `box`, so that it covers the `plotlyOutput` within.
- for the width problem, just resize you browser window. On mobile devices, switch to another `tabItem` and back to see the plot properly resized.

To be honest, it just doesn't feel right at this point. I think I'm going to try `ggplot2` or maybe `ggvis`  and write my own controls. `plotly` is not touch optimized, and has layout problems even in regular `Rmd`.

**Comment by cpsievert** [comment]
When using `ggplotly()`, you'll have to route the containers height/width the `ggplotly()` call. See here for an example https://github.com/ropensci/plotly/blob/master/inst/examples/shiny/ggplotly_sizing/app.R
