### ISSUE TITLE
Feature request: Make navigation across different pages available in navigation bar at top of page.

### ISSUE THREAD

**Issue by philstraforelli** [rstudio/shinydashboard#224]
I quite like the capability of having multiple pages up in the navigation board with `flexdashboard` as per [this example](https://beta.rstudioconnect.com/jjallaire/shiny-embedding/#module) where we have "Module", "Inline app", "External app". As I'm now migrating over to `shinydashboard` I was disappointed to realize that the pages are only available the in sidebar.

Would that option be available in an eventual future release of `shinydashboard`?

**Comment by bborgesr** [comment]
Sorry, this is unlikely to be implemented in shinydashboard. This is because this package is tied to a dashboard template, called [AdminLTE](https://adminlte.io/themes/AdminLTE/index2.html). So if there is something UI-specific that is not possible in AdminLTE, it is unlikely to be implemented for shinydashboard. This is one of those cases.

**Comment by philstraforelli** [comment]
@bborgesr Ah, I understand. Thanks for replying!

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
