### ISSUE TITLE
How to download rpivotTable ouput with shiny Dasboard

### ISSUE THREAD

**Issue by Lapchenkov** [rstudio/shinydashboard#226]
Hi!
i'm trying to save data from rpivotTable in my dashboardUI.
This part don't send data :

       PivotTable<-reactive({
        rpivotTable(data=cars, onRefresh=htmlwidgets::JS("function(config) {  
       Shiny.onInputChange('myPivotData', config); }"))
         })

I'm trying to do somethink like this:
https://stackoverflow.com/questions/44742017/download-rpivottable-ouput-in-shiny-dasboard

**Comment by bborgesr** [comment]
I've posted an answer to the Stack Overflow post. I've verified that there is no bug here, especially with regard to `shinydashboard` itself. Since this issue tracker is for reporting bugs or feature requests, I'll close it here and you can look up the answer in Stack Overflow if you're interested. 

In addition to Stack Overflow, I also recommend the [shiny-discuss](https://groups.google.com/forum/#!forum/shiny-discuss) forum for questions like these, looking for help with code.
