### ISSUE TITLE
Can we have a user sign-in feature in Shinydashboard? 

### ISSUE THREAD

**Issue by prateekjoshi565** [rstudio/shinydashboard#227]
I have created a shiny app using Shinydashboard and have deployed it on a local server. I want to make it password protected but just could not find any solution. It would be of great help if there is a feature in Shinydashboard to do that.

Thanks

**Comment by bborgesr** [comment]
I don't know what type of server you are running, but authentication is usually a feature of the application server, like Shiny Server Pro or RStudio Connect. The commercial versions of both software products offer authentication, as do the paid versions of shinyapps.io. Browse through [RStudio's products page](https://www.rstudio.com/products/) if you want more info on the different options. 

If you want to implement passwords yourself, there is a `passwordInput()` function in Shiny, but this is not encrypted in any way, so it is not secure if you actually have sensitive information in your app. That said, if all you want to do is specify different views for different users (rather than protect sensitive info), you can use it in your app (either Shiny or shinydashboard). Here's an example on Stack Overflow of a possible approach: https://stackoverflow.com/questions/28987622/starting-shiny-app-after-password-input
