### ISSUE TITLE
Header and Footer

### ISSUE THREAD

**Issue by vikram-rawat** [rstudio/shinydashboard#237]
Need a way to add title at the top bar along with creating tabs at the top bar or inserting images

The Top bar looks empty and flat some of my clients wanted us to do this. But I had no idea how it could be done.

Can you please give us the flexibility with the top bar at the center. Please

**Comment by bborgesr** [comment]
There's no way to do this in shinydashboard, since it is based on [AdminLTE](https://adminlte.io/themes/AdminLTE/index2.html), which does not offer any way of doing that.

For your clients' needs, I think you'd be better off using shiny directly. The `shiny::navbarPage` function does what I think you want. Take a look at [this app](https://beta.rstudioconnect.com/content/2917/) for an example of a Shiny app, built with `navbarPage`.
