### ISSUE TITLE
plots on boxes are not re-rendered when hiding/showing the sidebar

### ISSUE THREAD

**Issue by Gaasmann** [rstudio/shinydashboard#62]
Hello,

I have a little dashboard displaying some ggplot2 graphs. When I modify the size of my browser, the body is recalculated and redrawn correclty.
But when I hide the sidebar with the button on the header, the boxes are re-sized but not the graphs themselves. The result is a well sized and drawn boxes with too small graph aligned to the left of each box.
The code for the body is the following:

``` R
bodyLayout <- function() {
        bl <- dashboardBody(
                tabItems(
                    tabItem(tabName = "tab1",
                        fluidRow(
                             h2(" status"),
                             renderVPbox("item1", item1_level),
                             renderVPbox("item2", item2_level)),
                        fluidRow(
                             renderVPbox("item3", item3_level),
                             renderVPbox("item4", item4_level))
                    ),
                    tabItem(tabName = "statistics",
                             h2("Statistics"),
                             fluidRow(
                                box(plotOutput("stat_ass_reg_month")),
                                box(plotOutput("stat_ass_reg_week"),width=6),
                                box(plotOutput("stat_ass_reg_day"),width=6),
                                box(plotOutput("stat_team_month"),width=6),
                                box(plotOutput("stat_team_month_ppt"),width=6),
                                box(plotOutput("stat_team_week"),width=6),
                                box(plotOutput("stat_team_day"),width=6)
                             )
                    )
              )
        )
}
```

Do you have an idea to fix this?

Thanks,
## 

Nicolas

**Comment by MarkDB001** [comment]
I have the same issue would be nice to have a fix for this.

**Comment by maxmoro** [comment]
Same here.. thanks

**Comment by aquacalc** [comment]
Same issue. Yet to find a work-around.

Is there a way to observe the sidebar show/hide event, and then code a re-draw of the plot?

**Comment by zhiboz** [comment]
It puzzled me quite a while until I found this issue report and got to know that I am not alone. Any workaround yet? A fix from the code base would be even better! Thanks!

**Comment by bborgesr** [comment]
@wch: I think that in order to fix this, we need to do a `$("window").trigger("resize")` when the sidebar is collapsed (detected by the body having class `sidebar-collapse`). This means that [this](https://github.com/rstudio/shiny/blob/master/srcjs/init_shiny.js#L389) gets triggered.

I tried adding `$("window").trigger("resize")` after each of these lines ([app.js#332](https://github.com/rstudio/shinydashboard/blob/master/inst/AdminLTE/app.js#L332) and [app.js#334](https://github.com/rstudio/shinydashboard/blob/master/inst/AdminLTE/app.js#L334)), but that didn't work...

**Comment by jpark711** [comment]
I am having a same problem. If this issue has been closed because it was fixed, please advise me of the solution.

**Comment by bborgesr** [comment]
Are you using the Github/development version of `shinydashboard`, installed with:

```r
devtools::install_github("rstudio/shinydashboard")
```

If so, that really shouldn't be happening. Can you provide a repro?

------

If you're using the CRAN version of `shinydashboard` installed with (`install.packages("shinydashboard")`), you need to switch over to the devel version, because we've got yet released this fix (it's coming in the next couple of weeks).

**Comment by aquacalc** [comment]
This (temporary?) fix worked for me:

http://stackoverflow.com/questions/36655640/shiny-dashboard-does-not-scale-well

**Comment by jpark711** [comment]
I have installed Shiny Dashboard by 
`install.packages('shinydashboard') `
With some extra search, I found a solution from the same thread as the one @aquacalc mentioned. 
As the development version that @bborgesr  revised in the past includes an identical line, I understand that it will work as well. Thank you both for prompt replies!

**Comment by Diniodoc** [comment]
Hi all,

i have a very similar problem.

I’m using different tabItems in my dashboardbody. When I’m switching the active tab while the rendering and resizing process from the previous tab was not finished the same sizing issue appears when switching back to the first tab later.

Is there a special trigger for switching tabs to build a script like @aquacalc mentioned?

`    tags$script('      
      $(".sidebar-toggle").on("click",function(){
        $(window).trigger("resize");
      })'
    )`
